default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: kaizen

test:
  <<: *default
  database: kaizen

production:
  <<: *default
  database: kaizen
