default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: kaizen_dev

test:
  <<: *default
  database: kaizen_test

production:
  <<: *default
  database: kaizen_prod
